site_name: DOES VTT
site_url: https://cris.vtt.fi/en/organisations/ba4206-design-and-operation-of-energy-systems
logo: assets/DOES_Logo.png
nav:
  - Home: index.md
  - Overview: github_does_tools.md
  - Our Tools: our_tools.md
  - Hertta: Hertta.md
  - Tools Comparison: tool_comparison.md
theme: readthedocs

plugins:
  - mkdocs-video

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  homepage: https://cris.vtt.fi/en/organisations/ba4206-design-and-operation-of-energy-systems
